# Generated by Django 2.2.4 on 2019-08-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapi', '0002_usertasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
