# Generated by Django 2.2.4 on 2019-08-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapi', '0003_user_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='alias',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
